[pytest]
asyncio_default_fixture_loop_scope= function
markers =
    unit: marks test as unit tests that should can be ran at any time
    e2e: marks tests as e2e (deselect with '-m "not e2e"')
    slow: marks the test as slow (deselect with '-m "not slow"')